import { useEffect, useState } from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { UserPlus, Key, Mail, Phone, User, Users } from "lucide-react";
import { api } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";

const emptyForm = {
  pinToken: "",
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  accountNumber: "",
  referralEmail: "",
  position: "",
  paymentMethod: "",
};

const AddUser = () => {
  const { user, refreshUser } = useAuth();
  const [formData, setFormData] = useState(emptyForm);
  const { toast } = useToast();

  useEffect(() => {
    setFormData((prev) => ({ ...prev, referralEmail: user?.email || "" }));
  }, [user?.email]);

  const handleChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const emptyField = Object.entries(formData).find(([_, value]) => !value);
    if (emptyField) {
      toast({ title: "Error", description: "Please fill all fields", variant: "destructive" });
      return;
    }

    try {
      const result = await api("/api/accounts/activate/", {
        method: "POST",
        body: JSON.stringify(formData),
      });
      await refreshUser();
      toast({
        title: "Account Activated",
        description: `${result.login_email} can now log in with email as both login and password.`,
      });
      setFormData((prev) => ({ ...emptyForm, referralEmail: prev.referralEmail }));
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Activation failed", variant: "destructive" });
    }
  };

  return (
    <DashboardLayout>
      <div className="mx-auto max-w-2xl space-y-6 animate-fade-in">
        <h1 className="flex items-center gap-2 font-display text-2xl font-bold text-foreground">
          <UserPlus className="h-6 w-6 text-primary" />
          Add New User
        </h1>

        <Card className="nexo-card-glow border-border/50">
          <CardHeader>
            <CardTitle className="text-lg font-display">Account Activation</CardTitle>
            <p className="text-sm text-muted-foreground">Use one approved pin code from My Pins. The new user will log in with `email / email`.</p>
          </CardHeader>
          <CardContent>
            <div className="mb-4 rounded-lg border border-secondary/20 bg-secondary/5 p-3 text-sm">
              <p className="mb-2 font-semibold text-foreground">Activation requirements:</p>
              <ul className="space-y-1 text-muted-foreground">
                <li>Approved pin token generated by the backend</li>
                <li>New user email, phone, and payment account number</li>
                <li>Your own referral email and preferred side</li>
              </ul>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label>Pin Token</Label>
                <div className="relative">
                  <Key className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="Paste approved pin code"
                    value={formData.pinToken}
                    onChange={(e) => handleChange("pinToken", e.target.value)}
                    className="pl-10 font-mono"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>First Name</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                    <Input placeholder="First name" value={formData.firstName} onChange={(e) => handleChange("firstName", e.target.value)} className="pl-10" />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label>Last Name</Label>
                  <Input placeholder="Last name" value={formData.lastName} onChange={(e) => handleChange("lastName", e.target.value)} />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Email</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input type="email" placeholder="user@email.com" value={formData.email} onChange={(e) => handleChange("email", e.target.value)} className="pl-10" />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Phone Number</Label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input placeholder="03XXXXXXXXX" value={formData.phone} onChange={(e) => handleChange("phone", e.target.value)} className="pl-10" />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Payment Account Number</Label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input placeholder="EasyPaisa / JazzCash number" value={formData.accountNumber} onChange={(e) => handleChange("accountNumber", e.target.value)} className="pl-10" />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Referral Email</Label>
                <div className="relative">
                  <Users className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input type="email" value={formData.referralEmail} readOnly className="pl-10 opacity-80" />
                </div>
                <p className="text-xs text-muted-foreground">This is locked to your logged-in account email and is sent automatically.</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Preferred Branch</Label>
                  <Select value={formData.position} onValueChange={(value) => handleChange("position", value)}>
                    <SelectTrigger><SelectValue placeholder="Select branch" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="left">Left</SelectItem>
                      <SelectItem value="right">Right</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Payment Method</Label>
                  <Select value={formData.paymentMethod} onValueChange={(value) => handleChange("paymentMethod", value)}>
                    <SelectTrigger><SelectValue placeholder="Select method" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="easypaisa">EasyPaisa</SelectItem>
                      <SelectItem value="jazzcash">JazzCash</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <Button type="submit" className="w-full font-semibold text-primary-foreground nexo-gradient">
                Activate Account
              </Button>
            </form>

            <div className="mt-4 rounded-lg border border-border/50 bg-muted/30 p-3 text-sm text-muted-foreground">
              <p className="mb-1 font-semibold text-foreground">Activation flow:</p>
              <p>1. Buy a pin from Pin Code Request.</p>
              <p>2. Wait for admin approval and backend pin generation.</p>
              <p>3. Copy one code from My Pins into the pin token field.</p>
              <p>4. Submit the new user details and activate the account.</p>
              <p>5. The new user signs in with email as both username and password.</p>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default AddUser;
