import { useState } from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { UserPlus, Key, Mail, Phone, User, Users } from "lucide-react";
import { api } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { glassCardClass, PageShell } from "@/components/PageShell";

const emptyForm = {
  pinToken: "",
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  accountNumber: "",
  bankName: "",
  referralEmail: "",
  position: "",
  paymentMethod: "",
};

const AddUser = () => {
  const { refreshUser } = useAuth();
  const [formData, setFormData] = useState(emptyForm);
  const { toast } = useToast();

  const handleChange = (field: string, value: string) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
      ...(field === "paymentMethod" && value !== "bank_account" ? { bankName: "" } : {}),
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const requiredFields = Object.entries(formData).filter(([key]) => formData.paymentMethod === "bank_account" || key !== "bankName");
    const emptyField = requiredFields.find(([_, value]) => !value);
    if (emptyField) {
      toast({ title: "Error", description: "Please fill all fields", variant: "destructive" });
      return;
    }

    try {
      const result = await api("/api/accounts/activate/", {
        method: "POST",
        body: JSON.stringify(formData),
      });
      await refreshUser();
      toast({
        title: "Account Activated",
        description: `${result.login_email} can now log in with email as both login and password.`,
      });
      setFormData(emptyForm);
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Activation failed", variant: "destructive" });
    }
  };

  return (
    <DashboardLayout>
      <PageShell
        icon={UserPlus}
        title="Add New User"
        description="Activate a new account with one approved pin code."
        maxWidth="max-w-4xl"
      >
        <Card className={glassCardClass}>
          <CardHeader>
            <CardTitle className="text-lg font-display">Account Activation</CardTitle>
            <p className="text-sm text-muted-foreground">Use one approved pin code from My Pins. The pin is consumed only after this activation succeeds. The new user will log in with `email / email`.</p>
          </CardHeader>
          <CardContent className="p-4 pt-0 sm:p-6 sm:pt-0">
            <div className="mb-5 rounded-xl border border-secondary/20 bg-secondary/10 p-4 text-sm">
              <p className="mb-2 font-semibold text-foreground">Activation requirements:</p>
              <ul className="grid gap-2 text-muted-foreground sm:grid-cols-3">
                <li>Approved pin token generated by the backend</li>
                <li>New user email, phone, and payment account number</li>
                <li>Your own referral email and preferred side</li>
              </ul>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label>Pin Token</Label>
                <div className="relative">
                  <Key className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="Paste approved pin code"
                    value={formData.pinToken}
                    onChange={(e) => handleChange("pinToken", e.target.value)}
                    className="pl-10 font-mono"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label>First Name</Label>
                  <div className="relative">
                    <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                    <Input placeholder="First name" value={formData.firstName} onChange={(e) => handleChange("firstName", e.target.value)} className="pl-10" />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label>Last Name</Label>
                  <Input placeholder="Last name" value={formData.lastName} onChange={(e) => handleChange("lastName", e.target.value)} />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Email</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input type="email" placeholder="user@email.com" value={formData.email} onChange={(e) => handleChange("email", e.target.value)} className="pl-10" />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Phone Number</Label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input placeholder="03XXXXXXXXX" value={formData.phone} onChange={(e) => handleChange("phone", e.target.value)} className="pl-10" />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Payment Account Number</Label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input placeholder={formData.paymentMethod === "bank_account" ? "Bank account / IBAN number" : "EasyPaisa / JazzCash number"} value={formData.accountNumber} onChange={(e) => handleChange("accountNumber", e.target.value)} className="pl-10" />
                </div>
              </div>

              {formData.paymentMethod === "bank_account" && (
                <div className="space-y-2">
                  <Label>Bank Name</Label>
                  <Input placeholder="Enter bank name" value={formData.bankName} onChange={(e) => handleChange("bankName", e.target.value)} />
                </div>
              )}

              <div className="space-y-2">
                <Label>Referral Email</Label>
                <div className="relative">
                  <Users className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input type="email" value={formData.referralEmail} onChange={(e) => handleChange("referralEmail", e.target.value)} className="pl-10" />
                </div>
                <p className="text-xs text-muted-foreground">The approved pin belongs to your account, so this should be your own email.</p>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label>Preferred Branch</Label>
                  <Select value={formData.position} onValueChange={(value) => handleChange("position", value)}>
                    <SelectTrigger><SelectValue placeholder="Select branch" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="left">Left</SelectItem>
                      <SelectItem value="right">Right</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Payment Method</Label>
                  <Select value={formData.paymentMethod} onValueChange={(value) => handleChange("paymentMethod", value)}>
                    <SelectTrigger><SelectValue placeholder="Select method" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="easypaisa">EasyPaisa</SelectItem>
                      <SelectItem value="jazzcash">JazzCash</SelectItem>
                      <SelectItem value="bank_account">Bank Account</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <Button type="submit" className="w-full font-semibold text-primary-foreground nexo-gradient">
                Activate Account
              </Button>
            </form>

            <div className="mt-5 rounded-xl border border-white/60 bg-background/70 p-4 text-sm text-muted-foreground">
              <p className="mb-1 font-semibold text-foreground">Activation flow:</p>
              <p>1. Buy a pin from Pin Code Request.</p>
              <p>2. Wait for admin approval and backend pin generation.</p>
              <p>3. Copy one code from My Pins into the pin token field.</p>
              <p>4. Submit the new user details and activate the account. Only a successful activation marks the pin as used.</p>
              <p>5. The new user signs in with email as both username and password.</p>
            </div>
          </CardContent>
        </Card>
      </PageShell>
    </DashboardLayout>
  );
};

export default AddUser;
